export const traitList = [
  { code : 'A00',
    ico : 'A00',
    type : '',
    name : '',
    desc : '',
    effect : '',
  },
  { code : 'A01',
    ico : 'A01',
    type : 'C',
    name : '야심가',
    desc : '이 인물은 야심가입니다. 남들보다 높은 목표를 가지고 있으며, 목표를 이루기 위해 누구보다 발 빠르게 나아갑니다.',
    effect : '군공/명성 50% 추가 획득. 매 턴 공작 회복치 +1\n다른 야심가와의 개인관계 -50',
  },
]